In [40]:
# 1. Write a Python Program to Add Two Matrices?
# *************************************************************************************************************************
# 1.
import numpy as np

def add_matrices(arr1,arr2,size):
    r = np.zeros(size)
    for i in range(size[0]):
        for j in range(size[1]):
            r[i][j] = arr1[i][j] + arr2[i][j]
    return r

if __name__ == "__main__":
    
    array_size = list(map(int,input('Enter the size of array:').split()))
    
    print('\nEnter the element of array1:\n')
    array1 = list(map(int, input().split()))[:array_size[0]*array_size[1]]

    print('Enter the element of array2:\n')
    array2 = list(map(int, input().split()))[:array_size[0]*array_size[1]]
        
    print('Sum of the two arrays is:\n')
    
    array1 = np.array(array1).reshape(array_size[0], array_size[1])
    array2 = np.array(array2).reshape(array_size[0], array_size[1])
    print(array1)
    print('    +')
    print(array2)
    print('    =')
    print(add_matrices(array1, array2, array_size))

Enter the size of array:4 3

Enter the element of array1:

1 23 4 32 5 45 65 67 87 89 12 32
Enter the element of array2:

21 32 43 54 65 76 87 98 2 4 15 12
Sum of the two arrays is:

[[ 1 23  4]
 [32  5 45]
 [65 67 87]
 [89 12 32]]
    +
[[21 32 43]
 [54 65 76]
 [87 98  2]
 [ 4 15 12]]
    =
[[ 22.  55.  47.]
 [ 86.  70. 121.]
 [152. 165.  89.]
 [ 93.  27.  44.]]


In [49]:
# 2. Write a Python Program to Multiply Two Matrices?
# *************************************************************************************************************************
# 2.
import numpy as np

def mul_matrices(arr1,arr2,size):
    r = np.zeros(size)
    for i in range(size[0]):                        # rows of arr1
        for j in range(size[1]):                    # columns of arr2
            for k in range(size[0]):                # rows of arr2
                r[i][j] = r[i][j] + (arr1[i][k]* arr2[k][j])
    return r

if __name__ == "__main__":
    
    array_size = list(map(int,input('Enter the size of array:').split()))
    
    print('\nEnter the element of array1:\n')
    array1 = list(map(int, input().split()))[:array_size[0]*array_size[1]]

    print('Enter the element of array2:\n')
    array2 = list(map(int, input().split()))[:array_size[0]*array_size[1]]
        
    print('Product of the two arrays is:\n')
    
    array1 = np.array(array1).reshape(array_size[0], array_size[1])
    array2 = np.array(array2).reshape(array_size[0], array_size[1])
    print(array1)
    print('    *')
    print(array2)
    print('    =')
    print(mul_matrices(array1, array2, array_size))

Enter the size of array:3 3

Enter the element of array1:

1 2 3 4 5 6 7 8 9
Enter the element of array2:

1 2 3 4 5 6 7 8 9
Product of the two arrays is:

[[1 2 3]
 [4 5 6]
 [7 8 9]]
    *
[[1 2 3]
 [4 5 6]
 [7 8 9]]
    =
[[ 30.  36.  42.]
 [ 66.  81.  96.]
 [102. 126. 150.]]


In [85]:
# 3. Write a Python Program to Transpose a Matrix?
# *************************************************************************************************************************
# 3.
import numpy as np

def transpose(arr,size):
    r = np.zeros(size[::-1])                 # making the zero array in transposed form
    
    for i in range(size[0]):                 # rows
        for j in range(size[1]):             # columns
            r[j][i] = r[j][i] + arr[i][j]
    return r

if __name__ == "__main__":
    
    array_size = list(map(int,input('Enter the size of array:').split()))
    
    print('\nEnter the element of array:\n')
    array = list(map(int, input().split()))[:array_size[0]*array_size[1]]
        
    print('\nOriginal array:\n')
    
    array = np.array(array).reshape(array_size[0], array_size[1])
    print(array)
    print('\nAfter Transpose\n')
    print(transpose(array, array_size))

Enter the size of array:2 3

Enter the element of array:

1 2 3 4 5 6

Original array:

[[1 2 3]
 [4 5 6]]

After Transpose

[[1. 4.]
 [2. 5.]
 [3. 6.]]


In [14]:
# 4. Write a Python Program to Sort Words in Alphabetic Order?
# *************************************************************************************************************************
# 4.
# here we are using Bubble sorting technique for sorting the list

def sorting(lst):
    for i in range(len(lst)-1):
        for j in range(i+1, len(lst)):
            if lst[i] > lst[j]:
                temp = lst[i]
                lst[i] = lst[j]
                lst[j] = temp
    return lst

if __name__ == '__main__':
    number_of_elements = int(input('Enter the number of elements: '))
    element_list = []
    for i in range(number_of_elements):
        element_list.append(input())
    print('List before sorting is : ',element_list)
    print('\nList after sorting is : ',sorting(element_list))

Enter the number of elements: 7
Arijit
Sonu
Sunidhi
Asha
Rafi
Shaan
Mohit
List before sorting is :  ['Arijit', 'Sonu', 'Sunidhi', 'Asha', 'Rafi', 'Shaan', 'Mohit']

List after sorting is :  ['Arijit', 'Asha', 'Mohit', 'Rafi', 'Shaan', 'Sonu', 'Sunidhi']


In [23]:
# 5. Write a Python Program to Remove Punctuation From a String?
# *************************************************************************************************************************
# 5.

def punctuation(string):
    punctuation_marks = '''!()-[]{};?@#$%:'"\,./^&*_'''
    for i in string:
        if i in punctuation_marks:
            string = string.replace(i,'')
    return string

if __name__ == '__main__':
    string = input('Enter the string:\n ')
    print('\nString without punctuation is:\n',punctuation(string))

Enter the string:
 Hi!! My name is: Nee@les#h J@ais^w&a*l?

String without punctuation is:
 Hi My name is Neelesh Jaiswal
